description: https://github.com/Tsukino-uwu/TsukiAPYaml
name: Tsukino

progression_balancing: 50

supported_games_only: false
async: false
per_game_name: true

game:
  Pokemon Emerald: 0
  Super Metroid Map Rando: 1
  A Link to the Past: 0
  Pokemon FireRed and LeafGreen: 0
  Super Mario 64: 0
  Dark Souls III: 0

requires:
  version: 0.5.1

plando: items

Pokemon Emerald:
  accessibility: full
  goal: champion
  badges: completely_random
  hms: completely_random
  key_items: true
  bikes: true
  event_tickets: true
  rods: true
  overworld_items: true
  hidden_items: false
  npc_gifts: true
  berry_trees: true
  dexsanity: false
  trainersanity: false
  item_pool_type: shuffled
  require_itemfinder: true
  require_flash: both
  elite_four_requirement: badges
  elite_four_count: 8
  norman_requirement: badges
  norman_count: 4
  legendary_hunt_catch: false
  legendary_hunt_count: 3
  allowed_legendary_hunt_encounters:
    - Groudon
    - Kyogre
    - Rayquaza
    - Latios
    - Latias
    - Regirock
    - Registeel
    - Regice
    - Ho-Oh
    - Lugia
    - Deoxys
    - Mew
  wild_pokemon: completely_random
  starters: completely_random
  trainer_parties: completely_random
  force_fully_evolved: 100
  legendary_encounters: completely_random
  misc_pokemon: completely_random
  types: vanilla
  abilities: follow_evolutions
  ability_blacklist:
    - Wonder Guard
    - Arena Trap
    - Shadow Tag
    - Magnet Pull
    - Truant
    - Cacophony
  level_up_moves: randomized
  move_match_type_bias: 0
  move_normal_type_bias: 0
  tm_tutor_compatibility: 100
  hm_compatibility: 100
  tm_tutor_moves: false
  reusable_tms_tutors: true
  move_blacklist:
    - Minimize
    - Double Team
    - Protect
    - Substitute
    - Detect
    - Sand-Attack
    - Smokescreen
  min_catch_rate: 255
  guaranteed_catch: true
  normalize_encounter_rates: true
  exp_modifier: 300
  blind_trainers: true
  purge_spinners: false
  match_trainer_levels: off
  match_trainer_levels_bonus: 0
  double_battle_chance: 0
  better_shops: true
  extra_boulders: true
  extra_bumpy_slope: true
  modify_118: true
  free_fly_location: true
  hm_requirements: fly_without_badge
  turbo_a: true
  receive_item_messages: progression
  remote_items: true
  music: false
  fanfares: false
  death_link: true
  enable_wonder_trading: true
  easter_egg: EMERALD SECRET
  start_inventory: {}

Super Metroid Map Rando:
  accessibility: full
  remote_items: 'true'
  death_link:
    disable: 0
    enable_survive: 50
  preset:
    basic: 50
    medium: 0
    hard: 0
    veryhard: 0
    expert: 0
    extreme: 0
    insane: 0
    beyond: 0
    custom: 0
  techs: []
  strats: []
  item_pool: full
  custom_item_pool: Missile
  shinespark_tiles: 26
  heated_shinespark_tiles: 29
  shinecharge_leniency_frames: 90
  resource_multiplier: 100
  gate_glitch_leniency: 14
  door_stuck_leniency: 2
  escape_timer_multiplier: 300
  start_location_mode: randomroom
  phantoon_proficiency: 50
  draygon_proficiency: 25
  ridley_proficiency: 10
  botwoon_proficiency: 50
  mother_brain_proficiency: 50
  save_animals: maybe
  early_save: 'true'
  ultra_low_qol: 'false'
  quality_of_life: max
  objectives: bosses
  doors_mode: ammo
  area_assignment: randomized
  supers_double: 'true'
  mother_brain: short
  escape_enemies_cleared: 'true'
  escape_refill: 'true'
  escape_movement_items: 'true'
  mark_map_stations: 'true'
  room_outline_revealed: 'true'
  transition_letters: 'true'
  item_markers: 3tiered
  item_dots_disappear: 'true'
  all_items_spawn: 'true'
  buffed_drops: 'true'
  acid_chozo: 'true'
  fast_elevators: 'true'
  fast_doors: 'true'
  fast_pause_menu: 'true'
  respin: 'true'
  infinite_space_jump: 'true'
  momentum_conservation: 'true'
  wall_jump: collectible
  etank_refill: full
  maps_revealed: hidden
  map_layout:
    tame: 50
    wild: 0
  energy_free_shinesparks: 'false'
  etank_color_red: 222
  etank_color_green: 56
  etank_color_blue: 148
  reserve_hud_style: revamped
  vanilla_screw_attack_animation: vanilla
  palette_theme:
    vanilla: 50
    areathemed: 0
  tile_theme:
    none: 50
    scrambled: 0
  music: areathemed
  disable_beeping: vanilla
  shaking: vanilla
  shot: x
  jump: a
  dash: b
  item_select: y
  item_cancel: select
  angle_up: r
  angle_down: l
  spin_lock_buttons: ['L', 'Up', 'X', 'R']
  quick_reload_buttons: ['L', 'Select', 'Start', 'R']
  moonwalk: 'false'

A Link to the Past:
  accessibility: items
  goal: ganon
  mode: open
  glitches_required: no_glitches
  dark_room_logic: lamp
  open_pyramid: goal
  crystals_needed_for_gt: '7'
  crystals_needed_for_ganon: '7'
  triforce_pieces_mode: available
  triforce_pieces_percentage: '150'
  triforce_pieces_required: '20'
  triforce_pieces_available: '30'
  triforce_pieces_extra: '10'
  entrance_shuffle: vanilla
  entrance_shuffle_seed: random
  big_key_shuffle: original_dungeon
  small_key_shuffle: original_dungeon
  key_drop_shuffle: 'true'
  compass_shuffle: original_dungeon
  map_shuffle: original_dungeon
  restrict_dungeon_item_on_boss: 'false'
  item_pool: easy
  item_functionality: easy
  enemy_health: easy
  enemy_damage: default
  progressive: 'on'
  swordless: 'false'
  dungeon_counters: 'on'
  retro_bow: 'false'
  retro_caves: 'false'
  hints: 'on'
  scams: 'off'
  boss_shuffle: none
  pot_shuffle: 'false'
  enemy_shuffle: 'false'
  killable_thieves: 'true'
  bush_shuffle: 'false'
  shop_item_slots: '0'
  randomize_shop_inventories: default
  shuffle_shop_inventories: 'false'
  include_witch_hut: 'false'
  randomize_shop_prices: 'false'
  randomize_cost_types: 'false'
  shop_price_modifier: '100'
  shuffle_capacity_upgrades: 'on'
  bombless_start: 'false'
  shuffle_prizes: general
  tile_shuffle: 'false'
  glitch_boots: 'true'
  beemizer_total_chance: '0'
  beemizer_trap_chance: '60'
  timer: none
  countdown_start_time: '10'
  red_clock_time: '-2'
  blue_clock_time: '2'
  green_clock_time: '4'
  death_link: 'true'
  allow_collect: 'true'
  ow_palettes: default
  uw_palettes: default
  hud_palettes: default
  sword_palettes: default
  shield_palettes: default
  heartbeep: normal
  heartcolor: red
  quickswap: 'true'
  menuspeed: normal
  music: 'true'
  reduceflashing: 'true'
  triforcehud: normal
  start_inventory: {}
  start_inventory_from_pool: {}
  misery_mire_medallion: random
  turtle_rock_medallion: random

Pokemon FireRed and LeafGreen:
  accessibility: full
  game_version: firered
  goal: elite_four
  kanto_only: 'false'
  random_starting_town: 'false'
  shuffle_badges: 'true'
  shuffle_hidden: 'off'
  extra_key_items: 'false'
  trainersanity: none
  dexsanity: none
  famesanity: 'false'
  shuffle_fly_destination_unlocks: 'off'
  pokemon_request_locations: 'false'
  shuffle_running_shoes: start_with
  card_key: vanilla
  island_passes: split
  split_teas: 'false'
  itemfinder_required: required
  flash_required: required
  fame_checker_required: 'true'
  viridian_city_roadblock: vanilla
  pewter_city_roadblock: brock
  modify_world_state:
    - Remove Cerulean Roadblocks
    - Modify Route 10
    - Block Tower
    - Route 12 Boulders
    - Modify Route 12
    - Open Silph
    - Remove Saffron Rockets
    - Route 23 Trees
    - Modify Route 23
    - Block Vermilion Sailing
  additional_dark_caves: []
  remove_badge_requirement:
    - Fly
  oaks_aide_route_2: 0
  oaks_aide_route_10: 0
  oaks_aide_route_11: 0
  oaks_aide_route_16: 0
  oaks_aide_route_15: 0
  viridian_gym_requirement: badges
  viridian_gym_count: 7
  route22_gate_requirement: badges
  route22_gate_count: 7
  route23_guard_requirement: badges
  route23_guard_count: 7
  elite_four_requirement: badges
  elite_four_count: 8
  elite_four_rematch_count: 8
  cerulean_cave_requirement: badges
  cerulean_cave_count: 8
  level_scaling: 'off'
  modify_trainer_levels: 0
  force_fully_evolved: never
  wild_pokemon: completely_random
  wild_pokemon_groups: none
  wild_pokemon_blacklist: []
  starters: completely_random
  starter_blacklist: []
  trainers: completely_random
  trainer_blacklist: []
  legendary_pokemon: completely_random
  misc_pokemon: completely_random
  types: vanilla
  abilities: follow_evolutions
  ability_blacklist:
    - Wonder Guard
    - Arena Trap
    - Truant
    - Shadow Tag
    - Plus
    - Minus
  moves: randomized
  move_blacklist: []
  hm_compatibility: full
  tm_tutor_compatibility: full
  tm_tutor_moves: 'false'
  reusable_tm_tutors: 'true'
  min_catch_rate: 255
  all_pokemon_seen: 'true'
  exp_modifier: 300
  starting_money: 3000
  better_shops: 'true'
  free_fly_location: any
  town_map_fly_location: 'off'
  randomize_music: 'false'
  randomize_fanfares: 'false'
  game_options:
    Auto Run: 'Off'
    Battle Scene: 'Off'
    Battle Style: Set
    Bike Music: 'On'
    Blind Trainers: 'On'
    Button Mode: Help
    Encounter Rates: Vanilla
    Experience: Custom
    Frame: 1
    Guaranteed Catch: 'On'
    Item Messages: Progression
    Low HP Beep: 'On'
    Show Effectiveness: 'On'
    Skip Fanfares: 'Off'
    Sound: Mono
    Surf Music: 'On'
    Text Speed: Instant
    Turbo A: 'On'
  provide_hints: 'false'

Super Mario 64:
  accessibility: full
  area_rando: 'off'
  buddy_checks: 'true'
  exclamation_boxes: 'true'
  progressive_keys: 'false'
  enable_coin_stars: 'true'
  enable_move_rando: 'true'
  move_rando_actions:
    - Triple Jump
    - Long Jump
    - Backflip
    - Side Flip
    - Wall Kick
    - Dive
    - Ground Pound
    - Kick
    - Climb
    - Ledge Grab
  strict_cap_requirements: 'true'
  strict_cannon_requirements: 'true'
  strict_move_requirements: 'true'
  amount_of_stars: 120
  first_bowser_star_door_cost: 7
  basement_star_door_cost: 25
  second_floor_star_door_cost: 42
  mips1_cost: 12
  mips2_cost: 42
  stars_to_finish: 58
  death_link: 'true'
  completion_type: last_bowser_stage

Dark Souls III:
  accessibility: full
  early_banner: early_global
  late_basin_of_vows: after_small_lothric_banner
  late_dlc: 'off'
  death_link: 'true'
  enable_dlc: 'true'
  enable_ngp: 'true'
  random_starting_loadout: 'true'
  require_one_handed_starting_weapons: 'true'
  auto_equip: 'true'
  lock_equip: 'false'
  no_equip_load: 'true'
  no_weapon_requirements: 'true'
  no_spell_requirements: 'true'
  randomize_infusion: 'true'
  randomize_infusion_percentage: '2'
  randomize_weapon_level: all
  randomize_weapon_level_percentage: '33'
  max_levels_in_5: '5'
  max_levels_in_10: '10'
  smooth_soul_items: 'true'
  smooth_upgrade_items: 'true'
  smooth_upgraded_weapons: 'true'
  randomize_enemies: 'false'
  simple_early_bosses: 'true'
  scale_enemies: 'true'
  randomize_mimics_with_enemies: 'false'
  randomize_small_crystal_lizards_with_enemies: 'false'
  reduce_harmless_enemies: 'false'
  all_chests_are_mimics: 'false'
  impatient_mimics: 'false'
  exclude_locations:
  - Hidden
  - Miscellaneous
  - Small Crystal Lizards
  - Small Souls
  - Upgrade
  excluded_location_behavior: forbid_useful
  missable_location_behavior: forbid_useful
  start_inventory: {}
  min_levels_in_5: random
  min_levels_in_10: random

triggers:
  - option_name: supported_games_only
    option_result: true
    options:
      null:
        game:
          Pokemon Emerald: 1
          A Link to the Past: 1
          Super Mario 64: 1
          Dark Souls III: 1

  - option_name: async
    option_result: true
    options:
      Pokemon Emerald:
        dexsanity: true
        wild_pokemon:
          completely_random: 50
        trainersanity: true
        goal: steven
        require_itemfinder:
          true: 50
        hidden_items:
          true: 50
        npc_gifts:
          true: 50
        berry_trees:
          true: 50
        guaranteed_catch:
          true: 50
        normalize_encounter_rates:
          true: 50
        remove_roadblocks: []
        plando_items: []

  - option_name: game
    option_result: Pokemon Emerald
    options:
      null:
        name: "TsukiPkmnEmrld{NUMBER}"

  - option_name: game
    option_result: Super Metroid Map Rando
    options:
      null:
        name: "TsukiMetroid{NUMBER}"

  - option_name: game
    option_result: A Link to the Past
    options:
      null:
        name: "TsukiALTTP{NUMBER}"

  - option_name: game
    option_result: Pokemon FireRed and LeafGreen
    options:
      null:
        name: "TsukiPkmnFrlg{NUMBER}"

  - option_name: game
    option_result: Super Mario 64
    options:
      null:
        name: "TsukiSM64{NUMBER}"

  - option_name: game
    option_result: Dark Souls III
    options:
      null:
        name: "TsukiDS3{NUMBER}"

  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: "Tsukino{NUMBER}"
