description: https://github.com/Tsukino-uwu/TsukiAPYaml
name: Tsukino

supported_games_only: false
async: false
per_game_name: true

game:
  Pokemon Emerald: 1
  Super Metroid: 0
  A Link to the Past: 0
  Pokemon FireRed and LeafGreen: 0

requires:
  version: 0.5.1

plando: items

Pokemon Emerald:
  progression_balancing: 50
  accessibility: full
  goal: champion
  badges: completely_random
  hms: completely_random
  key_items: true
  bikes: true
  event_tickets: true
  rods: true
  overworld_items: true
  hidden_items: false
  npc_gifts: true
  berry_trees: true
  dexsanity: false
  trainersanity: false
  item_pool_type: shuffled
  require_itemfinder: true
  require_flash: both
  elite_four_requirement: badges
  elite_four_count: 8
  norman_requirement: badges
  norman_count: 4
  legendary_hunt_catch: false
  legendary_hunt_count: 3
  allowed_legendary_hunt_encounters:
    - Groudon
    - Kyogre
    - Rayquaza
    - Latios
    - Latias
    - Regirock
    - Registeel
    - Regice
    - Ho-Oh
    - Lugia
    - Deoxys
    - Mew
  wild_pokemon: completely_random
  starters: completely_random
  trainer_parties: completely_random
  force_fully_evolved: 100
  legendary_encounters: completely_random
  misc_pokemon: completely_random
  types: vanilla
  abilities: follow_evolutions
  ability_blacklist:
    - Wonder Guard
    - Arena Trap
    - Shadow Tag
    - Magnet Pull
    - Truant
    - Cacophony
  level_up_moves: randomized
  move_match_type_bias: 0
  move_normal_type_bias: 0
  tm_tutor_compatibility: 100
  hm_compatibility: 100
  tm_tutor_moves: false
  reusable_tms_tutors: true
  move_blacklist:
    - Minimize
    - Double Team
    - Protect
    - Substitute
    - Detect
    - Sand-Attack
    - Smokescreen
  min_catch_rate: 255
  guaranteed_catch: true
  normalize_encounter_rates: true
  exp_modifier: 300
  blind_trainers: true
  purge_spinners: false
  match_trainer_levels: off
  match_trainer_levels_bonus: 0
  double_battle_chance: 0
  better_shops: true
  extra_boulders: true
  extra_bumpy_slope: true
  modify_118: true
  free_fly_location: true
  hm_requirements: fly_without_badge
  turbo_a: true
  receive_item_messages: progression
  remote_items: true
  music: false
  fanfares: false
  death_link: true
  enable_wonder_trading: true
  easter_egg: EMERALD SECRET
  start_inventory: {}

Super Metroid:
  progression_balancing: '50'
  accessibility: full
  start_inventory_removes_from_pool: 'false'
  preset: newbie
  start_location: landing_site
  remote_items: 'true'
  death_link: enable_survive
  max_difficulty: hardcore
  morph_placement: early
  hide_items: 'false'
  strict_minors: 'false'
  missile_qty: '30'
  super_qty: '20'
  power_bomb_qty: '10'
  minor_qty: '100'
  energy_qty: vanilla
  area_randomization: 'off'
  area_layout: 'false'
  doors_colors_rando: 'false'
  allow_grey_doors: 'false'
  boss_randomization: 'false'
  escape_rando: 'false'
  remove_escape_enemies: 'false'
  fun_combat: 'false'
  fun_movement: 'false'
  fun_suits: 'false'
  layout_patches: 'true'
  varia_tweaks: 'true'
  nerfed_charge: 'false'
  gravity_behaviour: vanilla
  elevators_speed: 'true'
  fast_doors: 'true'
  spin_jump_restart: 'true'
  rando_speed: 'true'
  infinite_space_jump: 'true'
  refill_before_save: 'true'
  hud: 'true'
  animals: 'false'
  no_music: 'false'
  random_music: 'true'
  tourian: fast
  custom_objective: 'false'
  custom_objective_list: random
  custom_objective_count: '4'
  objective: kill all G4
  relaxed_round_robin_cf: 'false'
  start_inventory: {}

A Link to the Past:
  progression_balancing: '50'
  accessibility: items
  goal: ganon
  mode: open
  glitches_required: no_glitches
  dark_room_logic: lamp
  open_pyramid: goal
  crystals_needed_for_gt: '7'
  crystals_needed_for_ganon: '7'
  triforce_pieces_mode: available
  triforce_pieces_percentage: '150'
  triforce_pieces_required: '20'
  triforce_pieces_available: '30'
  triforce_pieces_extra: '10'
  entrance_shuffle: vanilla
  entrance_shuffle_seed: random
  big_key_shuffle: original_dungeon
  small_key_shuffle: original_dungeon
  key_drop_shuffle: 'true'
  compass_shuffle: original_dungeon
  map_shuffle: original_dungeon
  restrict_dungeon_item_on_boss: 'false'
  item_pool: easy
  item_functionality: easy
  enemy_health: easy
  enemy_damage: default
  progressive: 'on'
  swordless: 'false'
  dungeon_counters: 'on'
  retro_bow: 'false'
  retro_caves: 'false'
  hints: 'on'
  scams: 'off'
  boss_shuffle: none
  pot_shuffle: 'false'
  enemy_shuffle: 'false'
  killable_thieves: 'true'
  bush_shuffle: 'false'
  shop_item_slots: '0'
  randomize_shop_inventories: default
  shuffle_shop_inventories: 'false'
  include_witch_hut: 'false'
  randomize_shop_prices: 'false'
  randomize_cost_types: 'false'
  shop_price_modifier: '100'
  shuffle_capacity_upgrades: 'on'
  bombless_start: 'false'
  shuffle_prizes: general
  tile_shuffle: 'false'
  glitch_boots: 'true'
  beemizer_total_chance: '0'
  beemizer_trap_chance: '60'
  timer: none
  countdown_start_time: '10'
  red_clock_time: '-2'
  blue_clock_time: '2'
  green_clock_time: '4'
  death_link: 'true'
  allow_collect: 'true'
  ow_palettes: default
  uw_palettes: default
  hud_palettes: default
  sword_palettes: default
  shield_palettes: default
  heartbeep: normal
  heartcolor: red
  quickswap: 'true'
  menuspeed: normal
  music: 'true'
  reduceflashing: 'true'
  triforcehud: normal
  start_inventory: {}
  start_inventory_from_pool: {}
  misery_mire_medallion: random
  turtle_rock_medallion: random

Pokemon FireRed and LeafGreen:
  progression_balancing: 50
  accessibility:
    full: 50
  game_version:
    firered: 50
  goal:
    elite_four: 50
  kanto_only:
    'false': 50
  random_starting_town:
    'false': 50
  shuffle_badges:
    'true': 50
  shuffle_hidden:
    'off': 50
  extra_key_items:
    'false': 50
  trainersanity:
    none: 50
  dexsanity:
    none: 50
  famesanity:
    'false': 50
  shuffle_fly_destination_unlocks:
    'off': 50
  pokemon_request_locations:
    'false': 50
  shuffle_running_shoes:
    start_with: 50
  card_key:
    vanilla: 50
  island_passes:
    split: 50
  split_teas:
    'false': 50
  itemfinder_required:
    required: 50
  flash_required:
    required: 50
  fame_checker_required:
    'true': 50
  viridian_city_roadblock:
    vanilla: 50
  pewter_city_roadblock:
    brock: 50
  modify_world_state:
    - Remove Cerulean Roadblocks
    - Modify Route 10
    - Block Tower
    - Route 12 Boulders
    - Modify Route 12
    - Open Silph
    - Remove Saffron Rockets
    - Route 23 Trees
    - Modify Route 23
    - Block Vermilion Sailing
  additional_dark_caves: []
  remove_badge_requirement:
    - Fly
  oaks_aide_route_2:
    0: 50
  oaks_aide_route_10:
    0: 50
  oaks_aide_route_11:
    0: 50
  oaks_aide_route_16:
    0: 50
  oaks_aide_route_15:
    0: 50
  viridian_gym_requirement:
    badges: 50
  viridian_gym_count:
    7: 50
  route22_gate_requirement:
    badges: 50
  route22_gate_count:
    7: 50
  route23_guard_requirement:
    badges: 50
  route23_guard_count:
    7: 50
  elite_four_requirement:
    badges: 50
  elite_four_count:
    8: 50
  elite_four_rematch_count:
    8: 50
  cerulean_cave_requirement:
    badges: 50
  cerulean_cave_count:
    8: 50
  level_scaling:
    'off': 50
  modify_trainer_levels:
    0: 50
  force_fully_evolved:
    never: 50
  wild_pokemon:
    completely_random: 50
  wild_pokemon_groups:
    none: 50
  wild_pokemon_blacklist: []
  starters:
    completely_random: 50
  starter_blacklist: []
  trainers:
    completely_random: 50
  trainer_blacklist: []
  legendary_pokemon:
    completely_random: 50
  misc_pokemon:
    completely_random: 50
  types:
    vanilla: 50
  abilities:
    follow_evolutions: 50
  ability_blacklist: []
  moves:
    randomized: 50
  move_blacklist: []
  hm_compatibility:
    full: 50
  tm_tutor_compatibility:
    full: 50
  tm_tutor_moves:
    'false': 50
  reusable_tm_tutors:
    'true': 50
  min_catch_rate:
    255: 50
  all_pokemon_seen:
    'true': 50
  exp_modifier:
    300: 50
  starting_money:
    3000: 50
  better_shops:
    'true': 50
  free_fly_location:
    any: 50
  town_map_fly_location:
    'off': 50
  randomize_music:
    'false': 50
  randomize_fanfares:
    'false': 50
  game_options:
    Auto Run: 'Off'
    Battle Scene: 'Off'
    Battle Style: Set
    Bike Music: 'On'
    Blind Trainers: 'On'
    Button Mode: Help
    Encounter Rates: Vanilla
    Experience: Custom
    Frame: 1
    Guaranteed Catch: 'On'
    Item Messages: Progression
    Low HP Beep: 'On'
    Show Effectiveness: 'On'
    Skip Fanfares: 'Off'
    Sound: Mono
    Surf Music: 'On'
    Text Speed: Instant
    Turbo A: 'On'
  provide_hints:
    'false': 50

triggers:
  - option_name: supported_games_only
    option_result: true
    options:
      null:
        game:
          Pokemon Emerald: 1
          Super Metroid: 1
          A Link to the Past: 1

  - option_name: async
    option_result: true
    options:
      Pokemon Emerald:
        dexsanity: true
        wild_pokemon:
          completely_random: 50
        trainersanity: true
        goal: steven
        require_itemfinder:
          true: 50
        hidden_items:
          true: 50
        npc_gifts:
          true: 50
        berry_trees:
          true: 50
        guaranteed_catch:
          true: 50
        normalize_encounter_rates:
          true: 50
        remove_roadblocks: []
        plando_items: []

  - option_name: game
    option_result: Pokemon Emerald
    options:
      null:
        name: "TsukiPkmnEmrld{NUMBER}"

  - option_name: game
    option_result: Super Metroid
    options:
      null:
        name: "TsukiMetroid{NUMBER}"

  - option_name: game
    option_result: A Link to the Past
    options:
      null:
        name: "TsukiALTTP{NUMBER}"

  - option_name: game
    option_result: Pokemon FireRed and LeafGreen
    options:
      null:
        name: "TsukiPkmnFrlg{NUMBER}"

  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: "Tsukino{NUMBER}"
